"""Generate `docs/schema.md` from the real schema modules.

Run this script whenever `sensortap/schema/*.py` changes, so the published
vocabulary/enum/field reference in `docs/schema.md` cannot drift from the
code that defines it:

    python docs/generate_schema_reference.py > docs/schema.md

This should eventually become a pre-commit hook or CI check (there is no
docs build pipeline in this project today, so for now it's a manual step).
"""

from __future__ import annotations

import dataclasses

from sensortap.schema.enums import Availability, Delivery, Dtype, Status
from sensortap.schema.kinds import FAN_SPEED_UNIT, KIND_VOCABULARY
from sensortap.schema.reading import Reading
from sensortap.schema.rate import RateSpec
from sensortap.schema.sensor_info import SensorInfo
from sensortap.schema.validate import _NULLABLE_FIELDS
from sensortap.schema.version import SCHEMA_VERSION


def _dataclass_field_names(cls: type) -> list[str]:
    return [f.name for f in dataclasses.fields(cls)]


def _render_enum(name: str, description: str, members: type) -> str:
    lines = [f"### `{name}`", "", description, ""]
    for member in members:
        lines.append(f"- `{member.value}`")
    lines.append("")
    return "\n".join(lines)


def _render_fields(name: str, cls: type, nullable: frozenset[str] | None = None) -> str:
    lines = [f"### `{name}` fields", ""]
    for field_name in _dataclass_field_names(cls):
        if nullable is not None:
            suffix = " (nullable)" if field_name in nullable else ""
        else:
            suffix = ""
        lines.append(f"- `{field_name}`{suffix}")
    lines.append("")
    return "\n".join(lines)


def generate() -> str:
    parts: list[str] = []

    parts.append("# Schema reference")
    parts.append("")
    parts.append(
        "This page is generated by `docs/generate_schema_reference.py` "
        "directly from `sensortap/schema/*.py`. Do not hand-edit it -- "
        "re-run the script instead, so this page can never drift from the "
        "code (Req 2.12)."
    )
    parts.append("")

    parts.append(f"## Schema version")
    parts.append("")
    parts.append(f"Current `SCHEMA_VERSION`: `{SCHEMA_VERSION}`")
    parts.append("")

    parts.append(f"## `kind` vocabulary ({len(KIND_VOCABULARY)} members)")
    parts.append("")
    parts.append(
        "The closed set of `kind` values a `SensorInfo.kind` may hold "
        "(Req 2.12). Adding a member is a MINOR schema bump; removing or "
        "re-meaning one is MAJOR."
    )
    parts.append("")
    for kind in sorted(KIND_VOCABULARY):
        parts.append(f"- `{kind}`")
    parts.append("")
    parts.append(f"Fan speed unit (`FAN_SPEED_UNIT`, pinned for the `fan` kind): `{FAN_SPEED_UNIT}`")
    parts.append("")

    parts.append("## Enums")
    parts.append("")
    parts.append(_render_enum("Dtype", "The shape discriminator of a sensor's values.", Dtype))
    parts.append(_render_enum("Delivery", "How a Backend hands values to its Adapter.", Delivery))
    parts.append(
        _render_enum(
            "Availability",
            "The availability state of a sensor reported in `SensorInfo`.",
            Availability,
        )
    )
    parts.append(_render_enum("Status", "The status of a single `Reading`.", Status))

    parts.append("## Records")
    parts.append("")
    parts.append(
        _render_fields("SensorInfo", SensorInfo, nullable=_NULLABLE_FIELDS)
    )
    parts.append(_render_fields("Reading", Reading))
    parts.append(_render_fields("RateSpec", RateSpec))

    parts.append("## Test suite coverage")
    parts.append("")
    parts.append(
        "The automated Test_Suite (including the Conformance_Check in "
        "`sensortap/adapters/conformance.py`) validates schema compliance, "
        "sensor id stability, and the adapter-facing error contract. It "
        "does **not** cover, and cannot substitute for manual/hardware "
        "verification of:"
    )
    parts.append("")
    parts.append("- physical hardware readings (whether reported values match reality)")
    parts.append("- per-vendor driver behaviour")
    parts.append("- OS permission prompts")
    parts.append("- Stream stability beyond 60 seconds")
    parts.append("- performance/throughput benchmarking")
    parts.append("")

    return "\n".join(parts) + "\n"


if __name__ == "__main__":
    print(generate(), end="")
